#ifdef RGB_MATRIX_ENABLE
#   define RGB_DISABLE_WHEN_USB_SUSPENDED
#endif

#define DEBOUNCE 30

#define LED_CAPS_LOCK_PIN 17

#define QUICK_TAP_TERM 69
#define TAPPING_TERM 300
#define TAPPING_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD
